@hostname = localhost
@port = 9925
@host = {{hostname}}:{{port}}
@contentType = application/json

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "registration_info"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "get_fingerprint"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "create_schema",
    "schema": "test"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "drop_schema",
    "schema": "test"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "describe_schema",
    "schema": "test"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "create_table",
    "schema": "test",
    "table": "table1",
    "hash_attribute": "id"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "insert",
    "schema": "test",
    "table": "table1",
    "records": [
        {
            "name": "Louis",
            "age": 43
        },
        {
            "name": "Cornelia",
            "age": 41
        }
    ]
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "update",
    "schema": "test",
    "table": "table1",
    "records": [
        {
            "name": "Louis",
            "age": 43,
            "location": "Elsau",
            "id": "2a35ecf8-26e1-4526-8e49-d2a78ba53433"
        },
        {
            "name": "Cornelia",
            "age": 41,
            "id": "f7b9dd17-e79f-4e58-afe6-fcaa5d39237b"
        }
    ]
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "delete",
    "schema": "test",
    "table": "table1",
    "hash_values": ["2a35ecf8-26e1-4526-8e49-d2a78ba53433"]
}

###


POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "search_by_value",
    "schema": "test",
    "table": "table1",
    "search_attribute": "age",
    "search_value": "4*",
    "get_attributes": ["*"]
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "sql",
    "sql": "insert into test.table1 (name, age) values ('Giulia', 7)"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "sql",
    "sql": "update test.table1 set age = 27 where name = 'Giulia'"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "sql",
    "sql": "delete from test.table1 where name = 'Giulia'"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
    "operation": "sql",
    "sql": "select * from test.table1"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"csv_data_load",
	"schema":"test",
	"action": "insert",
	"table":"table1",
	"data":"id,name,section,country,image\n1,ENGLISH POINTER,British and Irish Pointers and Setters,GREAT BRITAIN,http://www.fci.be/Nomenclature/Illustrations/001g07.jpg\n2,ENGLISH SETTER,British and Irish Pointers and Setters,GREAT BRITAIN,http://www.fci.be/Nomenclature/Illustrations/002g07.jpg\n3,KERRY BLUE TERRIER,Large and medium sized Terriers,IRELAND,\n"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"describe_table",
	"schema":"test",
	"table":"table1"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"get_job",
	"id":"f5e1e68b-200e-4449-8bbc-0d5fb092bfe9"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"search_jobs_by_start_date",
    "from_date": "2020-11-16",
    "to_date": "2020-11-18"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"add_role",
	"role":"cluster_user",
	"permission":{
	  "cluster_user": true
    }
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"alter_role",
	"role":"cluster_user",
    "id": "2c0baa93-f513-45a2-9e4a-1a3dc1384623",
	"permission":{
	  "cluster_user": true
    }
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"list_roles"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"drop_role",
    "id": "a8d3916c-ff67-4509-ad95-a364ae9f96f9"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"list_users"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"add_user",
    "role": "13f2ed5a-f972-42e3-9919-2368313718c0",
    "username": "louis",
    "password": "test",
    "active": true
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"alter_user",
    "role": "13f2ed5a-f972-42e3-9919-2368313718c0",
    "username": "louis",
    "password": "test2",
    "active": true
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"drop_user",
    "username": "louis3332"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"user_info"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"read_log",
	"limit":1000,
	"start":0,
	"from":"2017-07-10",
	"until":"2021-07-11",
	"order":"desc"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"describe_all"
}

###

POST http://127.0.0.1:9926 HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"describe_all"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"add_node",
    "name": "node2",
    "host": "127.0.0.1",
    "port": 1112,
    "subscriptions": [
        {
            "channel": "test:table1",
            "publish": true,
            "subscribe": false
        }
    ]
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"cluster_status"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"remove_node",
    "name": "node2"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"read_transaction_log",
    "schema": "test",
    "table": "table1"
}

###

POST http://{{host}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Basic HDB_ADMIN:password

{
	"operation":"system_information"
}

###